kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.name }}
  annotations:
      "helm.sh/resource-policy": keep
spec:
  storageClassName: openebs-lvmpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.volume.size }}
